### ISSUE TITLE
Crash when plane is destroyed over water

### ISSUE THREAD

**Issue by Stifling-Bossness** [Stifling-Bossness/Aircraft#13]

**Comment by Stifling-Bossness** [comment]
Current proposed solution: Kill the player if aircraft is destroyed over water.

**Comment by Stifling-Bossness** [comment]
(If anyone knows how to do this, please do help out, I suck at Lua)

**Comment by InflamedSebi** [comment]
I think it would be fun to have an ejection seat + parachute when the plane gets destroyed. If u manage to glide away from water you survive, else u die ...
Ofc the parachute should be invincible since attacking parachutists from aircraft in distress is a war crime under the Protocol I addition to the 1949 Geneva Conventions. Even Bitters should respect that :D

Not quite sure how hard this would be to implement, but it would at least get rid of this bug in a very clean way ...

**Comment by snouz** [comment]
Maybe it was the case before, but now you just die by collision and just respawn. Not a bug anymore.
